#:schema node_modules/wrangler/config-schema.json
name = "workers"
main = "src/worker.ts"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

env = { }

[triggers]
crons = [ ]

